### ISSUE TITLE
Change to `require` calls

### ISSUE THREAD

**Issue by tbranyen** [chesles/combynify#2]
Currently I'm embedding all partials and templates, instead of rewriting as `require` calls that will memoize automatically.  This will result in faster and smaller bundles.

**Comment by tbranyen** [comment]
Started on the work here: https://github.com/chesles/combynify/commit/2f5a15938bc70a548cc99a9579fe36cb0514cb9a

Major issue is that doing the dynamic require's happens in Node-land not Browserify which means the transform isn't happening recursively.

**Comment by kadamwhite** [comment]
"memoize automatically", _i.e._ be parsed by browserify and therefore passed through combynify as well automatically?

**Comment by tbranyen** [comment]
Yeah, basically I want to avoid inlining templates wherever possible and instead treat them as modules and hook into the browserify resolution.  Unfortunately I wasn't able to find a way around the transform issue.  If template A gets transformed by combynify and depends on template B, if I swap it for a `require('/path/to/template/b.html')`, browserify will parse that require and fail.  Is probably a bug that should be reported to Browserify.

**Comment by tbranyen** [comment]
So with https://github.com/chesles/combynify/blob/master/index.js#L73-L79 and my latest PR everything seems to work great inside my application.  If you could test @kadamwhite I'll publish a new version once you can okay it.

**Comment by tbranyen** [comment]
Cool got confirmation, closing this issue.
