### ISSUE TITLE
Partials are required to use .html extenion

### ISSUE THREAD

**Issue by kadamwhite** [chesles/combynify#6]
I noticed that the partials resolution code assumes a .html extension, despite that the middleware otherwise supports `.combyne`, etcetera. I have created a small repo to demonstrate the issue:

https://github.com/kadamwhite/combynify-extension-issue

**Comment by tbranyen** [comment]
Offending lines:
- https://github.com/chesles/combynify/blob/master/index.js#L55
- https://github.com/chesles/combynify/blob/master/index.js#L61

**Comment by tbranyen** [comment]
Fixed.  Update to combynify 2.0.0 for all the goodness.

**Comment by kadamwhite** [comment]
I've deleted the demo repo linked in this issue, so in the admittedly _highly_ unlikely event somebody needs to replicate this in the future,

<details>
 <summary>here is the example code!</summary>

## Issue Description

`template.combyne` includes the code `{%partial partial %}`; a file named `partial.combyne` is present in the views directory.

Running `npm test` (alias for `browserify -t combynify main.js`) demonstrates that combynify [assumes `.html` extension for all partials](https://github.com/chesles/combynify/blob/master/index.js#L55-L61): it will not locate the partial unless the extension is changed to `.html`.

**Files to use when reproducing**:

`main.js`:
```js
var template = require( './views/template.combyne' );

console.log( template.render({}) );
```
`views/partial.combyne`:
```
<p>I am a partial</p>
```
`views/template.combyne`:
```
{%partial partial %}
```
`package.json`:
```json
{
  "name": "combynify-extension-issue",
  "private": true,
  "scripts": {
    "test": "browserify -t combynify main.js"
  },
  "license": "MIT",
  "dependencies": {
    "browserify": "^11.0.1",
    "combynify": "^1.0.0"
  }
}
```

</details>
